# Generated by Django 3.2.6 on 2022-12-02 12:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='введите имя (максимальное количество символов - 64)', max_length=64, verbose_name='имя')),
                ('last_name', models.CharField(help_text='введите фамилию (максимальное количество символов - 64)', max_length=64, verbose_name='фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='укажите номер телефона', max_length=128, region=None, verbose_name='телефон')),
                ('email', models.EmailField(help_text='укажите адрес электронной почты', max_length=254, unique=True, verbose_name='электронная почта')),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', help_text='выберите роль пользователя', max_length=15, verbose_name='роль')),
                ('image', models.ImageField(blank=True, help_text='разместите ваше фото', null=True, upload_to='photos/', verbose_name='фото')),
                ('is_active', models.BooleanField(help_text='укажите активность аккаунта', verbose_name='аккаунт активен')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
